dist: focal

language: python

python:
  - "3.12"


install:
  - pip install -r requirements.txt  # Install all dependencies from requirements.txt

script:
  - black --check .  # Validate formatting
  - flake8  # Lint code
  - coverage run --source=polls manage.py test polls.testsuite

after_success:
  - coveralls  # Send test coverage report to Coveralls

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  app: "personal-app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-982534388341"
  on:
    branch: main  # Deploy only from the main branch
